stages:
  - lint
  - build
  - benchmark
  - install
  - doc
  - deploy

lint-ocaml:
  stage: lint
  image: registry.gitlab.com/dannywillems/docker-ocamlformat:0.15.0
  before_script:
    - eval $(opam env)
  script:
    - ocamlformat --check benchmark/*.ml*
    - ocamlformat --check common/*.ml*
    - ocamlformat --check src/gen/*.ml*
    - ocamlformat --check src/js/*.ml*
    - ocamlformat --check src/js-gen/*.ml*
    - ocamlformat --check src/unix/*.ml*
    - ocamlformat --check src/unix/bindings/*.ml*
    - ocamlformat --check src/virtual/*.ml*
    - ocamlformat --check test/*.ml*
    - ocamlformat --check test/js/*.ml*
    - ocamlformat --check test/js-gen/*.ml*
  rules:
    - when: always

lint-js:
  image: node:lts
  stage: lint
  before_script:
    - cd .ci
    - npm install -d
  script:
    - ./node_modules/eslint/bin/eslint.js -c .eslintrc.js ../test/js/node/run.js
    - ./node_modules/eslint/bin/eslint.js -c .eslintrc.js ../test/js/browser/run.js
  rules:
    - when: always

.build-test: &build_definition
  stage: build
  before_script:
    # Required to get the right Rust version.
    - . $HOME/.cargo/env
    # Always update system package manager + setup OPAM env
    - sudo apt-get update
    - eval $(opam env)
    - opam update
    - opam depext -i -y conf-pkg-config conf-libffi
    # Install NVM for the JS test
    - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
    - export NVM_DIR="$HOME/.nvm"
    - . "$NVM_DIR/nvm.sh"
    - nvm install 14.12.0
    - nvm use 14.12.0
    # List versions and environments
    - rustc --version
    - ocaml --version
    - opam --version
    - node --version
    - echo $OPAM_SWITCH_PREFIX
  script:
    # Install external dependencies
    - opam depext -i -y zarith
    # Pin for later installation
    - opam pin add bls12-381-gen.dev . --no-action
    - opam pin add bls12-381.dev . --no-action
    - opam pin add bls12-381-unix.dev . --no-action
    - opam pin add bls12-381-js-gen.dev . --no-action
    - opam pin add bls12-381-js.dev . --no-action
    # Install the packages
    - opam install bls12-381-gen -y --with-test
    - opam install bls12-381 -y --with-test
    - opam install bls12-381-unix -y --with-test
    - opam install bls12-381-js-gen -y --with-test
    - opam install bls12-381-js -y --with-test
    - dune build @install
    - dune runtest
    # Additional test for the browser case of `js`. Tests are not automatic.
    # Only checking the stanza does work
    - dune build @test/js/browser/serve
  rules:
    - when: always

build-ocaml-4.08-rust-1.44.0:
  <<: *build_definition
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.08-1.44.0

build-ocaml-4.09-rust-1.44.0:
  <<: *build_definition
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.09-1.44.0

build-ocaml-4.10-rust-1.44.0:
  <<: *build_definition
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.10-1.44.0

build-ocaml-4.11-rust-1.44.0:
  <<: *build_definition
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.11-1.44.0

# Benchmarks
.benchmark: &benchmark_definition
  stage: benchmark
  before_script:
    # Required to get the right Rust version.
    - . $HOME/.cargo/env
    # Always update system package manager + setup OPAM env
    - sudo apt-get update && sudo apt-get upgrade -y
    - eval $(opam env)
    - opam repository set-url default https://opam.ocaml.org
    - opam update
    # List versions and environments
    - rustc --version
    - ocaml --version
    - opam --version
    - echo $OPAM_SWITCH_PREFIX
    # Depext
    - opam depext -i -y zarith conf-pkg-config conf-libffi
    # Pin for later installation
    - opam pin add bls12-381-gen.dev . --no-action
    - opam pin add bls12-381.dev . --no-action
    - opam pin add bls12-381-unix.dev . --no-action
    - opam pin add bls12-381-js-gen.dev . --no-action
    - opam pin add bls12-381-js.dev . --no-action
    # Install the packages
    - opam install bls12-381-gen -y --with-test
    - opam install bls12-381 -y --with-test
    - opam install bls12-381-unix -y --with-test
    - opam install bls12-381-js-gen -y --with-test
    - opam install bls12-381-js -y --with-test
  script:
    # Benchmark
    - opam install core_bench
    - dune build benchmark/bench_ec.exe
    - dune build benchmark/bench_ff.exe
    - dune build benchmark/bench_pairing.exe
  rules:
    - when: always

# Core bench 0.12.0 only available for 4.09. FIXME: update to other versions
benchmark-ocaml-4.09-rust-1.44.0:
  <<: *benchmark_definition
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.09-1.44.0

opam-install-and-remove:
  stage: install
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.09-1.44.0
  before_script:
    - . $HOME/.cargo/env
    # List versions and environments
    - rustc --version
    - ocaml --version
    - opam --version
    - echo $OPAM_SWITCH_PREFIX
    - opam repository set-url default https://opam.ocaml.org
    - opam update
  script:
    - opam pin add bls12-381-gen.dev . --no-action
    - opam pin add bls12-381.dev . --no-action
    - opam pin add bls12-381-js-gen.dev . --no-action
    - opam pin add bls12-381-js.dev . --no-action
    - opam pin add bls12-381-unix.dev . --no-action

    - opam depext bls12-381-gen -y -v
    - opam install bls12-381-gen -y -v --deps-only
    - opam install bls12-381-gen -y -v

    - opam depext bls12-381 -y -v
    - opam install bls12-381 -y -v --deps-only
    - opam install bls12-381 -y -v

    - opam depext bls12-381-js-gen -y -v
    - opam install bls12-381-js-gen -y -v --deps-only
    - opam install bls12-381-js-gen -y -v

    - opam depext bls12-381-js -y -v
    - opam install bls12-381-js -y -v --deps-only
    - opam install bls12-381-js -y -v

    - opam depext bls12-381-unix -y -v
    - opam install bls12-381-unix -y -v --deps-only
    - opam install bls12-381-unix -y -v

    - opam remove -a -y bls12-381-js
    - opam remove -a -y bls12-381-js-gen
    - opam remove -a -y bls12-381-unix
    - opam remove -a -y bls12-381
    - opam remove -a -y bls12-381-gen
  rules:
    - when: always

opam-install-and-remove-local-switch:
  stage: install
  image: registry.gitlab.com/dannywillems/docker-ocaml-rust:4.09-1.44.0
  before_script:
    # Run everything in a local switch
    - opam switch create ./ 4.09.1 --no-install
    - eval $(opam config env)
    # Load rust version
    - . $HOME/.cargo/env
    # List versions and environments
    - rustc --version
    - ocaml --version
    - opam --version
    - echo $OPAM_SWITCH_PREFIX
    - opam repository set-url default https://opam.ocaml.org
    - opam update
  script:
    - opam pin add bls12-381-gen.dev . --no-action
    - opam pin add bls12-381.dev . --no-action
    - opam pin add bls12-381-js-gen.dev . --no-action
    - opam pin add bls12-381-js.dev . --no-action
    - opam pin add bls12-381-unix.dev . --no-action

    - opam depext bls12-381-gen -y -v
    - opam install bls12-381-gen -y -v --deps-only
    - opam install bls12-381-gen -y -v

    - opam depext bls12-381 -y -v
    - opam install bls12-381 -y -v --deps-only
    - opam install bls12-381 -y -v

    - opam depext bls12-381-js-gen -y -v
    - opam install bls12-381-js-gen -y -v --deps-only
    - opam install bls12-381-js-gen -y -v

    - opam depext bls12-381-js -y -v
    - opam install bls12-381-js -y -v --deps-only
    - opam install bls12-381-js -y -v

    - opam depext bls12-381-unix -y -v
    - opam install bls12-381-unix -y -v --deps-only
    - opam install bls12-381-unix -y -v

    - opam remove -a -y bls12-381-js
    - opam remove -a -y bls12-381-js-gen
    - opam remove -a -y bls12-381-unix
    - opam remove -a -y bls12-381
    - opam remove -a -y bls12-381-gen
  rules:
    - when: always

doc:
  stage: doc
  image: ocaml/opam2:4.09
  before_script:
    - sudo apt-get update && sudo apt-get upgrade -y
    - eval $(opam env)
    - opam repository set-url default https://opam.ocaml.org
    - opam update
    - opam depext -i -y zarith conf-libffi conf-rust conf-perl conf-pkg-config
    - sudo apt-get install m4 -y
    - opam install odoc -y
    - opam install . -y --with-test
  script:
    - dune build @doc
    - cp -r _build/default/_doc/_html _odoc/
  artifacts:
    paths:
      - _odoc
  rules:
    - when: always

pages:
  stage: deploy
  image: ocaml/opam2:4.09
  script:
    - cp -r _odoc public/
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
